_BASE_: "../Base-Relation.yaml"
INPUT:
  RANDOM_FLIP: none
MODEL:
  RELATION_ON: True
  ROI_RELATION_HEAD:
    MSDN_MODULE:
      HIDDEN_DIM: 512
      NUM_ITERS: 3
      SHARE_PARAMS_EACH_ITER: True
    PREDICTOR: MSDNPredictor
SEED: 3407  # 10760659
SOLVER:
  BASE_LR: 0.02
  CHECKPOINT_PERIOD: 5000
  STEPS: (10000, 30000, )
  MAX_ITER: 60000
TEST:
  DETECTIONS_PER_IMAGE: 80
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./checkpoints/sgdet/X-101-FPN-MSDN"