"""
Extra configurations for SGG.
Modified from FCSGG.

"""
__author__ = "Hengyue Liu"
__copyright__ = "Copyright (c) 2021 Futurewei Inc."
__credits__ = ["Detectron2"]
__license__ = "MIT License"
__version__ = "0.1"
__maintainer__ = "Hengyue Liu"
__email__ = "onehothenry@gmail.com"

from detectron2.config import CfgNode as CN

def add_sgg_config(cfg: CN):
    """
    Add config for fcsgg.
    """
    _C = cfg

    # datasets
    _C.DATASETS.VAL = ("", )

    # model
    _C.MODEL.ROI_HEADS.NUM_CLASSES = 150
    _C.MODEL.ROI_HEADS.NUM_PREDICATES = 50

    # relation
    _C.MODEL.RELATION_ON = False
    _C.MODEL.ROI_RELATION_HEAD = CN()
    _C.MODEL.ROI_RELATION_HEAD.RELATION_ONLY = False
    _C.MODEL.ROI_RELATION_HEAD.USE_FREQ_BIAS = False
    _C.MODEL.ROI_RELATION_HEAD.USE_GT_BOX = False
    _C.MODEL.ROI_RELATION_HEAD.USE_GT_LABEL = False
    
    _C.MODEL.ROI_RELATION_HEAD.NUM_CLASSES = 150
    _C.MODEL.ROI_RELATION_HEAD.NUM_PREDICATES = 50
    _C.MODEL.ROI_RELATION_HEAD.MULTIPLE_PREDS = False
    _C.MODEL.ROI_RELATION_HEAD.IOU_THRESHOLD = 0.5
    _C.MODEL.ROI_RELATION_HEAD.LATER_NMS_PRED_THRES = 0.3

    _C.MODEL.ROI_RELATION_HEAD.FG_IOU_THRESHOLD = 0.5
    _C.MODEL.ROI_RELATION_HEAD.REQUIRE_BOX_OVERLAP = False
    _C.MODEL.ROI_RELATION_HEAD.NUM_SAMPLES_PER_GT_REL = 4
    _C.MODEL.ROI_RELATION_HEAD.BATCH_SIZE_PER_IMAGE = 1000
    _C.MODEL.ROI_RELATION_HEAD.POSITIVE_FRACTION = 0.25
    _C.MODEL.ROI_RELATION_HEAD.MAX_PROPOSAL_PAIRS = 4096
    _C.MODEL.ROI_RELATION_HEAD.MERGE_PREDICATE_NODES = False

    _C.MODEL.ROI_RELATION_HEAD.POOLING_ALL_LEVELS = True
    _C.MODEL.ROI_RELATION_HEAD.USE_UNION_FEATURES = True

    _C.MODEL.ROI_RELATION_HEAD.PREDICTOR = 'MSDNPredictor'
    _C.MODEL.ROI_RELATION_HEAD.CONTEXT_POOLING_DIM = 2048

    _C.MODEL.ROI_RELATION_HEAD.MSDN_MODULE = CN()
    _C.MODEL.ROI_RELATION_HEAD.MSDN_MODULE.HIDDEN_DIM = 512
    _C.MODEL.ROI_RELATION_HEAD.MSDN_MODULE.NUM_ITERS = 3
    _C.MODEL.ROI_RELATION_HEAD.MSDN_MODULE.GATE_WIDTH = 128
    _C.MODEL.ROI_RELATION_HEAD.MSDN_MODULE.SHARE_PARAMS_EACH_ITER = True

    _C.MODEL.ROI_RELATION_HEAD.IMP_MODULE = CN()
    _C.MODEL.ROI_RELATION_HEAD.IMP_MODULE.HIDDEN_DIM = 512
    _C.MODEL.ROI_RELATION_HEAD.IMP_MODULE.NUM_ITERS = 3

    _C.TEST.ROI_RELATION_HEAD = CN()
    _C.TEST.ROI_RELATION_HEAD.REQUIRE_OVERLAP = False
