_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("vg_train", )
  TEST: ("vg_test", )
  # VAL: ("vg_val", )
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
MODEL:
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: (0.23232838, 0.63365731, 1.28478321, 3.15089189)
  MASK_ON: False
  META_ARCHITECTURE: "GeneralizedRCNNWithRelation"
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [57.375, 57.120, 58.395]
  RELATION_ON: False
  RESNETS:
    DEPTH: 101
    NUM_GROUPS: 32
    STRIDE_IN_1X1: False
    WIDTH_PER_GROUP: 8
  ROI_BOX_HEAD:
    FC_DIM: 4096
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    IOU_THRESHOLDS: [0.5]
    NAME: "RelationalROIHeads"
    NUM_CLASSES: 150
    POSITIVE_FRACTION: 0.5
  WEIGHTS: "/home/dcs405a/victchang/sgg/checkpoints/detection/model_final_68b088.pkl"
SEED: 3407  # 10760659
SOLVER:
  BASE_LR: 2e-3
  STEPS: (70000, 120000)
  MAX_ITER: 180000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./checkpoints/detection/X-101-FPN"
